id: PF4B56A76
initial_creation_type: ocr
source_metadata:
  volumes:
    acbcdc7d898c40a08d8a72ad97347adf:
      base_file: v040.txt
      image_group_id: I1PD95885
      title: འཇིགས་པ་བརྒྱད་ལས་སྐྱོབ་པ།
      total_pages: 1648
      volume_number: 40
